### ISSUE TITLE
Adding Searchkit

### ISSUE THREAD

**Issue by fsxdrone** [brygrill/wab-react-webpack#1]
Hi...how to add searchkit to the mix and how to get started? below is the blurb from package.json and did yarn to update the dependencies... the website doesn't load...it just spins on the localhost:3000.

  "dependencies": {
    "creatable": "^3.0.3",
    "react-select": "^1.2.1",
    "lodash": "^4.17.4",
    "prop-types": "^15.6.1",    
    "searchkit": "^2.3.0-9"    
  },

**Comment by brygrill** [comment]
Hey, I made a branch to test out searchkit https://github.com/brygrill/wab-react-webpack/tree/searchkit

To get it working, I removed the webpack lodash plugin as it was conflicting with searchkit. I didnt test searching a cluster or anything, but the components load. Hope it helps!

**Comment by fsxdrone** [comment]
That worked flawlessly....Thank you ...
