### ISSUE TITLE
How can I generate and load a vendor bundle for environments disallowed use of a CDN

### ISSUE THREAD

**Issue by ryanewtaylor** [brygrill/wab-react-webpack#11]
Our environment disallows use of a CDN for importing resources, like React. As such we need to create additional vendor bundles. I'm still trying to figure out the how to do this within this template (as asked in [Generate vendor bundle with webpack loadable via AMD][here]). 

How might I go about this?

In addition, it may be helpful documentation to have as an optional resource loading method.

[here]: https://stackoverflow.com/questions/54776254/generate-vender-bundle-with-webpack-loadable-via-amd

**Comment by brygrill** [comment]
In the past, I've downloaded the packages and included a `vendors` folder outside of the build process. It is always a pain to load them properly through `amd`, but it is possible. I don't know if that would work for you?

**Comment by brygrill** [comment]
I have this requirement for a client and solved by downloading React and loading it locally. In my app directory, I created a folder called assets and saved react/react-dom in there. Then in Widget.js, I updated the paths to point to this local URL rather than the CDN:

```javascript
require({
  paths: {
    react: '/assets/react.production.min',
    'react-dom': '/assets/react-dom.production.min',
  },
});
```
