### ISSUE TITLE
How to subscribe redux store?

### ISSUE THREAD

**Issue by felixerdy** [brygrill/wab-react-webpack#3]
I'd like to subscribe the react app to my redux store. Usually I do this by
```jsx
import {store} from './store'

const render = () => ReactDOM.render(<App />);
store.subscribe(render);
render();
``` 
How do i access the `store` object in `Widget.js`? My store is saved and exported in `src/components/store/index.js`.

**Comment by felixerdy** [comment]
I just found a solution by myself, even though I am not sure whether it is the most elegant way:

##### index.js
```jsx
import App from './components/App';
import { store } from './components/store'

module.exports = {
    App,
    store
}
```

##### Widget.js
```jsx
...
define(
  [
    'dojo/_base/declare',
    'jimu/BaseWidget',
    'jimu/LayerInfos/LayerInfos',
    'esri/layers/FeatureLayer',
    'react',
    'react-dom',
    './App'
  ],
  (declare, BaseWidget, LayerInfos, FeatureLayer, React, ReactDOM, { App, store }) => {
...
        const root = document.getElementById('my-react-widget-root');
        const render = () => ReactDOM.render(<App wab={wab} esriJS={esriJS} />, root);
        store.subscribe(render)
        render()
...
```

**Comment by brygrill** [comment]
I haven't worked with redux extensively, but if that setup works, that's great.

Looking at the docs, could you make `components/App.js` your redux entry point and skip passing the store through `Widget.js` all together?

**Comment by felixerdy** [comment]
I also thought about that, but as I am also relatively new to React and Redux I will stay at my solution at first. There haven't been any issues so far
