### ISSUE TITLE
yarn install fails when using Node >= 10

### ISSUE THREAD

**Issue by ryanewtaylor** [brygrill/wab-react-webpack#7]
Running `yarn install` fails when using Node 10 or greater. I receive the following error

> error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9". Got "10.14.0"
>error Found incompatible module

I was able to resolve the issue by deleting node_modules and the yarn.lock file and re-running yarn install. This picked up newer versions of dependencies, the included a upath module not locked to a specific version of the node engine.

**Comment by brygrill** [comment]
thanks, was on 8 still. pushing fix to v1.2.1
